"""refactor_assessment_to_flat_columns

Revision ID: 3786103db680
Revises: 4da82daf65d7
Create Date: 2026-06-29 17:00:51.265073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3786103db680'
down_revision: Union[str, Sequence[str], None] = '4da82daf65d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop child tables first (have FK to assessment_aspects), then parent
    op.drop_table('portfolio_scores')
    op.drop_table('report_scores')
    op.drop_table('assessment_aspects')
    op.add_column('assessments', sa.Column('pai_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('pai_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('pkn_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('pkn_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('ind_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('ind_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('mat_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('mat_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('ipas_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('ipas_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('ing_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('ing_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('art_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('art_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('pjok_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('pjok_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('sun_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('sun_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('pro_score', sa.Float(), nullable=True))
    op.add_column('assessments', sa.Column('pro_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('pramuka_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('konsentrasi_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('motorik_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('interaksi_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('emosi_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('bina_diri_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('membaca_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('menulis_desc', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('berhitung_desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'berhitung_desc')
    op.drop_column('assessments', 'menulis_desc')
    op.drop_column('assessments', 'membaca_desc')
    op.drop_column('assessments', 'bina_diri_desc')
    op.drop_column('assessments', 'emosi_desc')
    op.drop_column('assessments', 'interaksi_desc')
    op.drop_column('assessments', 'motorik_desc')
    op.drop_column('assessments', 'konsentrasi_desc')
    op.drop_column('assessments', 'pramuka_desc')
    op.drop_column('assessments', 'pro_desc')
    op.drop_column('assessments', 'pro_score')
    op.drop_column('assessments', 'sun_desc')
    op.drop_column('assessments', 'sun_score')
    op.drop_column('assessments', 'pjok_desc')
    op.drop_column('assessments', 'pjok_score')
    op.drop_column('assessments', 'art_desc')
    op.drop_column('assessments', 'art_score')
    op.drop_column('assessments', 'ing_desc')
    op.drop_column('assessments', 'ing_score')
    op.drop_column('assessments', 'ipas_desc')
    op.drop_column('assessments', 'ipas_score')
    op.drop_column('assessments', 'mat_desc')
    op.drop_column('assessments', 'mat_score')
    op.drop_column('assessments', 'ind_desc')
    op.drop_column('assessments', 'ind_score')
    op.drop_column('assessments', 'pkn_desc')
    op.drop_column('assessments', 'pkn_score')
    op.drop_column('assessments', 'pai_desc')
    op.drop_column('assessments', 'pai_score')
    op.create_table('report_scores',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aspect_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numeric_score', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['assessment_aspects.id'], name=op.f('report_scores_ibfk_1')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('report_scores_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('portfolio_scores',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aspect_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('narrative_description', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['assessment_aspects.id'], name=op.f('portfolio_scores_ibfk_1')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('portfolio_scores_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('assessment_aspects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aspect_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('aspect_type', mysql.ENUM('quantitative', 'qualitative'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
