"""update_student_fields

Revision ID: 4da82daf65d7
Revises: 03b847df47e5
Create Date: 2026-06-29 16:36:47.784928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4da82daf65d7'
down_revision: Union[str, Sequence[str], None] = '03b847df47e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('school_name', sa.String(length=255), nullable=False))
    op.add_column('students', sa.Column('academic_year', sa.String(length=255), nullable=False))
    op.drop_column('students', 'guardian_name')
    op.drop_column('students', 'birth_date')
    op.drop_column('students', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gender', mysql.ENUM('M', 'F'), nullable=False))
    op.add_column('students', sa.Column('birth_date', sa.DATE(), nullable=False))
    op.add_column('students', sa.Column('guardian_name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('students', 'academic_year')
    op.drop_column('students', 'school_name')
    # ### end Alembic commands ###
