"""Initial database schema

Revision ID: 801ea6f3aadb
Revises: 
Create Date: 2026-06-27 10:02:42.234881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801ea6f3aadb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_aspects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aspect_name', sa.String(length=255), nullable=False),
    sa.Column('aspect_type', sa.Enum('quantitative', 'qualitative', name='aspect_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_number', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='student_gender'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('disability_category', sa.String(length=255), nullable=False),
    sa.Column('guardian_name', sa.String(length=255), nullable=False),
    sa.Column('class_level', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.Enum('Odd', 'Even', name='semester_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_student_number'), 'students', ['student_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.Enum('Odd', 'Even', name='semester_type'), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('aspect_id', sa.Integer(), nullable=False),
    sa.Column('narrative_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['assessment_aspects.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('development_status', sa.String(length=255), nullable=False),
    sa.Column('probability_score', sa.Float(), nullable=True),
    sa.Column('iep_recommendation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('report_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('aspect_id', sa.Integer(), nullable=False),
    sa.Column('numeric_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['assessment_aspects.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_scores')
    op.drop_table('prediction')
    op.drop_table('portfolio_scores')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_students_student_number'), table_name='students')
    op.drop_table('students')
    op.drop_table('assessment_aspects')
    # ### end Alembic commands ###
